import json

days = {
  31: {"category":"Workplace","title":"Day 31 - 영향력 있는 프레젠테이션","sub":"청중을 사로잡는 고급 발표 기술을 익힙니다.","videoId":"nU8m0287k_Y","kpis":[{"i":"🎤","v":"Impact","l":"임팩트","d":"청중의 마음을 움직이는 발표력"},{"i":"📊","v":"Structure","l":"구조화","d":"논리적 흐름으로 메시지를 전달하는 기술"}],"lessons":[{"t":"강력한 오프닝","d":"청중의 주목을 단번에 끄는 첫 문장 구성법"},{"t":"데이터 스토리텔링","d":"숫자와 통계를 생생한 이야기로 전환하기"},{"t":"Q&A 대응","d":"예상치 못한 질문에 침착하게 답하는 전략"},{"t":"시각 자료 활용","d":"슬라이드를 보조 도구로 활용하는 발표 화법"},{"t":"클로징 임팩트","d":"마지막 메시지로 강렬한 인상을 남기는 법"},{"t":"긴장 관리","d":"자신감 있는 보디랭귀지와 목소리 활용"}],"compare":[{"b":"Let me show you this slide.","g":"This data tells a compelling story about our growth."},{"b":"In conclusion...","g":"Let me leave you with one final thought that ties everything together."},{"b":"Any questions?","g":"I'd welcome any questions or perspectives you might have."},{"b":"I made this chart.","g":"This visualization highlights the key trend we need to address."},{"b":"Thank you for listening.","g":"Thank you for your time and thoughtful engagement today."},{"b":"I think...","g":"The evidence strongly suggests that..."}],"expr":[{"e":"Let me paint a picture for you.","k":"상상이 가도록 설명해 드릴게요.","x":"Let me paint a picture for you of what success looks like."},{"e":"The data speaks for itself.","k":"데이터가 모든 것을 말해줍니다.","x":"We don't need further justification; the data speaks for itself."},{"e":"I'd like to draw your attention to...","k":"이 부분에 주목해 주시기 바랍니다.","x":"I'd like to draw your attention to the trend in Q3."},{"e":"To put it simply...","k":"간단히 말씀드리자면...","x":"To put it simply, we need to act now."},{"e":"This brings me to my next point.","k":"이것이 다음 요점으로 이어집니다.","x":"This brings me to my next point about scalability."},{"e":"I'll open the floor to questions.","k":"이제 질문 시간을 갖겠습니다.","x":"I'll open the floor to questions after this summary."}]},
  32: {"category":"Communication","title":"Day 32 - 이메일과 문서의 격식","sub":"비즈니스 문서에서 격식과 명확성을 동시에 달성하는 법을 배웁니다.","videoId":"nU8m0287k_Y","kpis":[{"i":"✉️","v":"Precision","l":"정밀성","d":"모호함 없이 핵심을 전달하는 문장 구성"},{"i":"🎯","v":"Tone","l":"어조 조절","d":"상황에 맞는 격식 수준 선택하기"}],"lessons":[{"t":"이메일 오프닝","d":"상황별 적절한 인사말과 도입부 선택"},{"t":"요청의 완곡화","d":"명령이 아닌 협력을 구하는 정중한 표현"},{"t":"첨부 및 후속 조치","d":"문서 안내와 팔로우업을 매끄럽게 연결하기"},{"t":"거절과 반려","d":"관계를 보전하면서 No를 전달하는 기술"},{"t":"클로징 문구","d":"품격 있는 마무리 인사와 서명 작성법"},{"t":"CC와 수신자 예절","d":"이메일 참조 및 다수 수신자 에티켓"}],"compare":[{"b":"Send me the report.","g":"Could you please forward the report at your earliest convenience?"},{"b":"I don't agree.","g":"I have some reservations about this approach and would like to discuss further."},{"b":"See the attachment.","g":"Please find the attached document for your reference."},{"b":"Call me.","g":"Please feel free to reach out if you have any questions."},{"b":"I don't know.","g":"I'll look into this and revert to you shortly."},{"b":"OK.","g":"Noted, and I'll action this accordingly."}],"expr":[{"e":"I hope this email finds you well.","k":"잘 지내고 계시길 바랍니다.","x":"I hope this email finds you well; I wanted to follow up on our meeting."},{"e":"Please do not hesitate to reach out.","k":"언제든지 연락 주시기 바랍니다.","x":"Please do not hesitate to reach out should you need any clarification."},{"e":"As per our conversation...","k":"저희가 나눈 대화 내용대로...","x":"As per our conversation, I'm sending the revised proposal."},{"e":"I'll revert to you shortly.","k":"곧 다시 연락 드리겠습니다.","x":"I need to check with the team; I'll revert to you shortly."},{"e":"For your reference","k":"참고용으로 전달드립니다.","x":"Please find the attached document for your reference."},{"e":"Kindly note that...","k":"참고로 말씀드리자면...","x":"Kindly note that the deadline has been moved to Friday."}]},
  33: {"category":"Negotiation","title":"Day 33 - 협상의 시작과 포지셔닝","sub":"협상 테이블에서 유리한 위치를 선점하는 언어 전략을 배웁니다.","videoId":"eX1u6R6pWl4","kpis":[{"i":"🤝","v":"Leverage","l":"협상력","d":"상황을 유리하게 이끄는 언어적 포지셔닝"},{"i":"⚖️","v":"Balance","l":"균형 감각","d":"양측 모두 만족할 수 있는 합의점 도출"}],"lessons":[{"t":"관심사 파악하기","d":"상대방의 진짜 필요를 파악하는 질문 기술"},{"t":"앵커링 전략","d":"첫 제안을 유리하게 설정하는 앵커 기법"},{"t":"양보의 기술","d":"작은 것을 주고 큰 것을 얻는 교환 원칙"},{"t":"시간 활용","d":"침묵과 여유를 협상 도구로 활용하는 법"},{"t":"조건부 제안","d":"If-then 구조로 상호 이익을 창출하는 화법"},{"t":"합의 마무리","d":"협상 결과를 명확하게 문서화하는 표현"}],"compare":[{"b":"What's your price?","g":"What terms would you find most workable for this partnership?"},{"b":"That's too expensive.","g":"The investment is a bit beyond our current budget; is there any flexibility?"},{"b":"Let's compromise.","g":"Perhaps we can find a middle ground that works for both parties."},{"b":"I need a discount.","g":"Given the volume of our order, would you be open to a revised rate?"},{"b":"Deal or no deal?","g":"Are we aligned enough to move forward on this basis?"},{"b":"That's my final offer.","g":"This represents the best we can do within our current constraints."}],"expr":[{"e":"Let's find common ground.","k":"공통점을 찾아봅시다.","x":"I believe if we focus on shared goals, we can find common ground."},{"e":"What would it take to...?","k":"어떻게 하면 ...이 가능할까요?","x":"What would it take to expedite the delivery timeline?"},{"e":"We're prepared to move forward if...","k":"만약 ...이라면 저희는 진행할 준비가 되어 있습니다.","x":"We're prepared to move forward if the terms can be adjusted slightly."},{"e":"I appreciate your position.","k":"귀하의 입장 충분히 이해합니다.","x":"I appreciate your position; let me share our perspective as well."},{"e":"This is a deal-breaker for us.","k":"이것은 저희로서는 받아들이기 어려운 조건입니다.","x":"The exclusivity clause is a real deal-breaker for us at this stage."},{"e":"Let's revisit this point.","k":"이 부분으로 다시 돌아가 봅시다.","x":"I think we moved on too quickly; let's revisit this point."}]},
  34: {"category":"Cultural","title":"Day 34 - 글로벌 비즈니스 문화 이해","sub":"다양한 문화권의 비즈니스 관습과 에티켓을 이해하고 적응합니다.","videoId":"nU8m0287k_Y","kpis":[{"i":"🌍","v":"Awareness","l":"문화 인식","d":"다양한 문화권의 비즈니스 관습 이해"},{"i":"🤝","v":"Adaptability","l":"적응력","d":"상황에 따라 커뮤니케이션 스타일을 조절하는 능력"}],"lessons":[{"t":"High vs Low Context","d":"직접 화법과 간접 화법 문화권의 차이 이해"},{"t":"시간 개념의 차이","d":"Monochronic/Polychronic 문화권별 시간 관념"},{"t":"계층과 존중","d":"상하 관계를 나타내는 문화별 의사소통 방식"},{"t":"선물과 접대 문화","d":"선물 수수 에티켓과 비즈니스 식사 관습"},{"t":"협상 스타일 차이","d":"문화권별 협상 방식과 의사결정 구조 이해"},{"t":"정중한 질문과 거절","d":"문화적 맥락을 고려한 질문과 거절 방식"}],"compare":[{"b":"I disagree with the plan.","g":"I wonder if there might be an alternative approach worth exploring."},{"b":"Let's decide now.","g":"Perhaps we could take some time to reflect before finalizing our decision."},{"b":"That's wrong.","g":"There may be some nuances here worth considering together."},{"b":"Call me by my first name.","g":"Please feel free to address me by my given name."},{"b":"Just be direct with me.","g":"I value straightforward communication; please share your candid thoughts."},{"b":"We do it this way here.","g":"In our context, the convention tends to be a bit different."}],"expr":[{"e":"I'd like to be sensitive to your culture.","k":"귀 문화를 존중하고 싶습니다.","x":"I'd like to be sensitive to your culture; please correct me if I misstep."},{"e":"How do things typically work here?","k":"이곳에서는 보통 어떻게 진행되나요?","x":"I'm new to this market; how do things typically work here?"},{"e":"I want to make sure I'm not overstepping.","k":"제가 선을 넘지 않으려고 합니다.","x":"I want to make sure I'm not overstepping any cultural boundaries."},{"e":"Would this be appropriate in your context?","k":"귀 상황에서 이것이 적절할까요?","x":"Would a follow-up phone call be appropriate in your context?"},{"e":"I appreciate the cultural insight.","k":"문화적 통찰을 나눠주셔서 감사합니다.","x":"I appreciate the cultural insight; it's very helpful."},{"e":"Let's bridge our cultural differences.","k":"문화적 차이를 함께 좁혀나갑시다.","x":"By communicating openly, we can bridge our cultural differences effectively."}]},
  35: {"category":"Analytical","title":"Day 35 - 데이터와 논리로 설득하기","sub":"숫자와 근거를 효과적으로 활용하여 상대를 설득하는 기술입니다.","videoId":"t8A3a8j-sY8","kpis":[{"i":"📈","v":"Evidence","l":"근거 중심","d":"사실과 데이터로 뒷받침된 주장 구성"},{"i":"💡","v":"Persuasion","l":"설득력","d":"청중의 논리와 감성 모두에 호소하는 능력"}],"lessons":[{"t":"데이터 인용의 기술","d":"통계를 신뢰감 있게 인용하는 표현 방식"},{"t":"인과관계 설명","d":"Because, therefore, as a result 등 논리 연결사 활용"},{"t":"반례 선제 대응","d":"예상되는 반론을 먼저 언급하고 반박하는 기법"},{"t":"비유와 유추","d":"복잡한 개념을 친숙한 예시로 설명하는 법"},{"t":"감성적 마무리","d":"논리 이후 감성으로 행동을 촉구하는 기술"},{"t":"시각적 자료 연계","d":"차트·그래프와 말을 연결하는 구체적 표현"}],"compare":[{"b":"This is good.","g":"The data consistently shows a 32% improvement over the past two quarters."},{"b":"Everyone knows this.","g":"Research from MIT's Sloan School confirms this trend."},{"b":"So we should do this.","g":"Given this evidence, the most logical course of action would be..."},{"b":"Trust me.","g":"The numbers support what I'm suggesting here."},{"b":"It might work.","g":"Based on comparable case studies, the probability of success is high."},{"b":"Other companies do it.","g":"Industry benchmarks indicate that leading firms have adopted this model."}],"expr":[{"e":"The numbers tell a clear story.","k":"숫자가 분명한 이야기를 해주고 있습니다.","x":"Look at the trend; the numbers tell a clear story about our direction."},{"e":"This is backed by research.","k":"이것은 연구로 뒷받침됩니다.","x":"This approach is backed by research from Stanford and Harvard."},{"e":"Let's look at this objectively.","k":"이것을 객관적으로 살펴봅시다.","x":"Setting aside personal preferences, let's look at this objectively."},{"e":"The correlation is undeniable.","k":"상관관계는 부정할 수 없습니다.","x":"Between the two variables, the correlation is undeniable."},{"e":"Consider the following scenario.","k":"다음 시나리오를 생각해 보세요.","x":"Consider the following scenario: our costs double. How do we respond?"},{"e":"What does the evidence suggest?","k":"증거는 무엇을 시사합니까?","x":"Rather than assuming, let's ask: what does the evidence suggest?"}]},
  36: {"category":"Social","title":"Day 36 - 네트워킹 이벤트 고급 화법","sub":"행사 자리에서 자연스럽고 품격 있게 관계를 넓히는 기술입니다.","videoId":"0I12mA0EejE","kpis":[{"i":"🌐","v":"Network","l":"네트워크 확장","d":"진정성 있는 연결로 장기적 관계를 구축"},{"i":"💬","v":"Conversation","l":"대화 기술","d":"처음 만나는 사람과 깊이 있는 대화를 나누는 법"}],"lessons":[{"t":"자기소개의 격상","d":"단순한 직함 소개를 넘어선 가치 중심 자기 소개"},{"t":"대화 주제 발굴","d":"공통 관심사를 빠르게 찾아내는 질문 기술"},{"t":"경청과 기억","d":"이름과 내용을 기억하며 진정성을 보여주는 법"},{"t":"자연스러운 이동","d":"대화를 끊지 않고 다른 사람에게 이동하는 기술"},{"t":"연락처 교환","d":"자연스럽고 목적 있는 명함 및 연락처 교환"},{"t":"사후 Follow-up","d":"이벤트 후 관계를 지속하는 메시지 전략"}],"compare":[{"b":"I'm a marketer.","g":"I help companies tell their story in a way that resonates with their audience."},{"b":"Nice to meet you.","g":"It's great to finally connect in person; I've heard excellent things about your work."},{"b":"Here's my card.","g":"I'd love to stay in touch; shall we exchange details?"},{"b":"What do you do?","g":"What kind of work keeps you most energized these days?"},{"b":"I have to go now.","g":"It's been a pleasure; I don't want to monopolize too much of your evening."},{"b":"Let's keep in touch.","g":"I'll send you a note tomorrow with that resource I mentioned."}],"expr":[{"e":"I've followed your work for a while.","k":"오래 전부터 하시는 일 지켜봐 왔습니다.","x":"I've followed your work for a while; your last piece was truly insightful."},{"e":"What brings you to this event?","k":"이번 행사에는 어떤 계기로 참가하셨나요?","x":"What brings you to this event? Are you a member of this association?"},{"e":"We should grab coffee sometime.","k":"언제 커피 한잔 같이 해요.","x":"I'd love to hear more about your project; we should grab coffee sometime."},{"e":"I'll connect you with someone useful.","k":"도움이 될 분을 연결해 드릴게요.","x":"I know just the person for this; I'll connect you with someone useful."},{"e":"Let me follow up on that.","k":"그 부분은 제가 이후에 다시 연락 드리겠습니다.","x":"I don't have the answer right now, but let me follow up on that."},{"e":"You're exactly who I was hoping to meet.","k":"꼭 한번 만나뵙고 싶었던 분이세요.","x":"You're exactly who I was hoping to meet at this conference."}]},
  37: {"category":"Review","title":"Day 37 - 5~6주차 핵심 복습","sub":"31~36일차에 배운 개념을 통합하여 실전 적용 수준으로 체화합니다.","videoId":"0I12mA0EejE","kpis":[{"i":"📈","v":"Integration","l":"통합 정리","d":"각 상황에서 배운 표현을 연결하여 활용하기"}],"lessons":[{"t":"Presentation 핵심 복습","d":"임팩트 있는 오프닝과 데이터 스토리텔링 재점검"},{"t":"Email 격식 복습","d":"상황별 어조 조절과 정중한 요청 표현 재확인"},{"t":"Negotiation 핵심 복습","d":"포지셔닝과 조건부 제안 표현 강화"},{"t":"Cultural Awareness 복습","d":"문화별 커뮤니케이션 차이 재정리"},{"t":"Data Persuasion 복습","d":"논리적 인용과 연결사 활용 재확인"},{"t":"Networking 복습","d":"자기 소개와 후속 조치 표현 강화"}],"compare":[],"expr":[{"e":"Practice makes permanent.","k":"꾸준한 연습이 습관을 만듭니다.","x":"It's not just practice makes perfect; practice makes permanent."}]},
  38: {"category":"Leadership","title":"Day 38 - 리더의 언어: 동기부여","sub":"팀원에게 영감을 주고 자발적 동기를 이끌어내는 리더의 화법을 배웁니다.","videoId":"jWk7N6-W4Yw","kpis":[{"i":"🏆","v":"Inspire","l":"영감을 주는 힘","d":"팀의 잠재력을 끌어올리는 리더의 언어"},{"i":"💪","v":"Empower","l":"권한 부여","d":"팀원 스스로 주인의식을 갖게 하는 표현"}],"lessons":[{"t":"비전 제시","d":"팀이 나아갈 방향을 명확하고 설득력 있게 그리기"},{"t":"개인 인정과 칭찬","d":"일반적 칭찬이 아닌 구체적이고 의미 있는 인정"},{"t":"실패에 대한 격려","d":"좌절을 학습으로 전환시키는 리더의 반응 방식"},{"t":"책임감 부여","d":"부탁이 아닌 신뢰로 업무를 위임하는 기술"},{"t":"피드백의 예술","d":"성장 지향적 피드백을 주고받는 구체적 방법"},{"t":"팀 문화 형성","d":"심리적 안전감을 만드는 리더의 일상적 언어"}],"compare":[{"b":"Do this task.","g":"I'd trust you to take the lead on this; your expertise is exactly what we need."},{"b":"You made a mistake.","g":"Let's use this as a learning opportunity and figure out what we can do differently."},{"b":"Good job.","g":"Your approach to that client issue was exactly the kind of thinking we value here."},{"b":"We need to improve.","g":"I believe in our team's potential to achieve something great here."},{"b":"Why did this happen?","g":"Help me understand what factors contributed to this outcome."},{"b":"Just do better next time.","g":"What resources or support would help you succeed here?"}],"expr":[{"e":"I believe in your ability to handle this.","k":"이 일을 처리할 당신의 능력을 믿습니다.","x":"This is a challenging brief, but I believe in your ability to handle this."},{"e":"Your contribution matters.","k":"당신의 기여는 정말 중요합니다.","x":"Never doubt that your contribution matters to the success of this team."},{"e":"Let's learn from this together.","k":"이 경험에서 함께 배워봅시다.","x":"This didn't go as planned, but let's learn from this together."},{"e":"I have your back.","k":"제가 든든히 지원해 드리겠습니다.","x":"Take the risk; I have your back whatever happens."},{"e":"What would success look like for you?","k":"당신에게 성공은 어떤 모습인가요?","x":"Before we start, tell me: what would success look like for you?"},{"e":"Your voice matters here.","k":"여기서 당신의 목소리는 중요합니다.","x":"Don't hold back; your voice matters here and we want to hear it."}]},
  39: {"category":"Conflict","title":"Day 39 - 갈등 해소와 중재의 언어","sub":"직장 내 갈등을 품위 있게 해소하고 관계를 복원하는 언어 기술입니다.","videoId":"t8A3a8j-sY8","kpis":[{"i":"☮️","v":"Resolution","l":"갈등 해소","d":"충돌을 생산적 대화로 전환하는 기술"},{"i":"🤲","v":"Empathy","l":"공감 능력","d":"상대의 입장을 이해하고 존중하는 표현"}],"lessons":[{"t":"감정 인정하기","d":"상대방의 감정을 먼저 인정하는 공감 표현"},{"t":"나 전달법 활용","d":"비난 없이 내 불편함을 전달하는 I-statement"},{"t":"공통 목표 재확인","d":"갈등 속에서도 공유된 목표를 환기시키는 언어"},{"t":"중립적 사실 진술","d":"판단이 아닌 관찰에 기반한 상황 설명하기"},{"t":"해결책 공동 탐색","d":"일방적 해결이 아닌 협력적 해결책 모색"},{"t":"관계 복원 선언","d":"갈등 해소 후 관계 회복을 확인하는 표현"}],"compare":[{"b":"You always do this.","g":"I've noticed a pattern that I'd like to address; can we talk?"},{"b":"It's your fault.","g":"I feel concerned when this happens; can we explore what went wrong together?"},{"b":"You need to change.","g":"I'd love for us to find a way to work more effectively together."},{"b":"This is unfair.","g":"I feel this isn't quite aligned with what we originally agreed upon."},{"b":"Let's drop this.","g":"I'd like to make sure we've fully resolved this before moving on."},{"b":"I'm fine.","g":"I appreciate you asking, though I do have some lingering concerns."}],"expr":[{"e":"I hear where you're coming from.","k":"당신의 입장 충분히 이해합니다.","x":"I hear where you're coming from; I'd feel the same way in that situation."},{"e":"Let's focus on moving forward.","k":"앞으로 나아가는 것에 집중합시다.","x":"We can't change what happened, but let's focus on moving forward."},{"e":"Help me understand your perspective.","k":"당신의 관점을 이해할 수 있도록 도와주세요.","x":"Before I respond, help me understand your perspective on this."},{"e":"We're on the same team.","k":"우리는 같은 팀이에요.","x":"Whatever the disagreement, remember that we're on the same team."},{"e":"I want to make this right.","k":"이 상황을 제대로 해결하고 싶습니다.","x":"I value our relationship; I want to make this right."},{"e":"What would a fair outcome look like?","k":"공정한 결과는 어떤 모습일까요?","x":"Setting my position aside: what would a fair outcome look like to you?"}]},
  40: {"category":"Strategic","title":"Day 40 - 전략적 사고와 표현","sub":"장기적 관점에서 의사결정을 내리고 전달하는 전략가의 언어를 배웁니다.","videoId":"jWk7N6-W4Yw","kpis":[{"i":"🗺️","v":"Vision","l":"비전","d":"미래 방향을 명확히 설정하고 전달하는 능력"},{"i":"⚙️","v":"Systems","l":"시스템적 사고","d":"부분이 아닌 전체를 보는 통합적 사고 방식"}],"lessons":[{"t":"장기 vs 단기 균형","d":"즉각적 결과와 장기 목표 사이의 균형을 언어로 표현"},{"t":"리스크 프레이밍","d":"위험 요소를 명확하게 정의하고 완화책 제시"},{"t":"우선순위 설정","d":"제한된 자원 속에서 무엇이 가장 중요한지 설명하기"},{"t":"시나리오 플래닝","d":"가능한 미래를 미리 그리고 전달하는 전략적 화법"},{"t":"Trade-off 소통","d":"이점과 손실을 균형 있게 제시하는 성숙한 표현"},{"t":"의사결정 설명","d":"복잡한 결정의 근거를 명확하게 커뮤니케이션하는 법"}],"compare":[{"b":"Let's do option A.","g":"Considering the long-term implications, option A offers a more sustainable path."},{"b":"I don't know what will happen.","g":"While uncertainty remains, we've modeled three likely scenarios."},{"b":"This is risky.","g":"The risk is manageable if we establish clear mitigation measures."},{"b":"We can't decide now.","g":"To make an informed decision, we need to clarify one more variable."},{"b":"It's complicated.","g":"There are several interdependent factors we need to weigh carefully."},{"b":"Things change.","g":"We need to remain adaptive as the landscape continues to evolve."}],"expr":[{"e":"We need to think ten steps ahead.","k":"열 걸음 앞을 내다봐야 합니다.","x":"This is a dynamic environment; we need to think ten steps ahead."},{"e":"What are the downstream implications?","k":"이로 인한 하류 파급효과는 무엇인가요?","x":"Before committing, we should ask: what are the downstream implications?"},{"e":"This is a calculated risk.","k":"이것은 계산된 위험입니다.","x":"We're not acting blindly; this is a calculated risk with clear upside potential."},{"e":"Let's stress-test this assumption.","k":"이 가정을 검증해 봅시다.","x":"Before we commit, let's stress-test this assumption against edge cases."},{"e":"The strategic rationale is clear.","k":"전략적 근거는 명확합니다.","x":"The strategic rationale is clear; execution is now the key challenge."},{"e":"We need to align on priorities.","k":"우선순위에 대해 합의가 필요합니다.","x":"Before we dive in, we need to align on priorities as a team."}]},
}

# Days 41-60 with varied themes
themes_41_60 = [
  (41,"Scientific","AI와 기술 혁신 토론","첨단 기술 주제를 영어로 유창하게 논의하는 법을 배웁니다.","jWk7N6-W4Yw"),
  (42,"Academic","학술적 글쓰기와 인용","연구 기반의 격식 있는 글쓰기와 인용 스타일을 익힙니다.","nU8m0287k_Y"),
  (43,"Professional","성과 평가와 피드백","연간 평가와 성과 대화를 이끌어가는 심화 표현입니다.","nU8m0287k_Y"),
  (44,"Social","고급 유머와 위트","원어민식 위트와 유머를 자연스럽게 구사하는 기술입니다.","eX1u6R6pWl4"),
  (45,"Analytical","비판적 사고와 논증","강력한 논리와 반론 대응 기술을 심화 학습합니다.","t8A3a8j-sY8"),
  (46,"Lifestyle","여행과 글로벌 경험","여행 중 다양한 상황에서 쓰이는 세련된 표현입니다.","m_YshVbe2I4"),
  (47,"Cultural","문학과 영화 속 영어","원어민들이 즐기는 문화 콘텐츠를 통해 실용 표현을 익힙니다.","eX1u6R6pWl4"),
  (48,"Leadership","팀 빌딩과 심리적 안전감","신뢰와 개방성을 기반으로 한 팀 문화 언어를 배웁니다.","jWk7N6-W4Yw"),
  (49,"Negotiation","고급 협상 클로징","최종 합의를 이끌어내는 정교한 클로징 전략입니다.","eX1u6R6pWl4"),
  (50,"Review","Month 2 중간 복습","38~49일차의 핵심 개념을 통합적으로 복습합니다.","0I12mA0EejE"),
  (51,"Professional","글로벌 미팅 리드하기","국제 회의를 주도하는 고급 퍼실리테이션 기술입니다.","nU8m0287k_Y"),
  (52,"Strategic","변화 관리와 소통","조직 변화를 투명하고 공감 있게 전달하는 리더의 언어입니다.","jWk7N6-W4Yw"),
  (53,"Academic","아이디어 피칭의 예술","투자자와 이해관계자를 설득하는 피칭 기술을 익힙니다.","nU8m0287k_Y"),
  (54,"Communication","고급 경청과 질문 기술","대화의 주도권을 잡는 심층 경청 및 질문 프레임입니다.","t8A3a8j-sY8"),
  (55,"Descriptive","고급 메타포와 은유","복잡한 아이디어를 강렬하게 전달하는 은유 기법입니다.","0I12mA0EejE"),
  (56,"Social","공감과 감사의 표현","깊은 유대를 형성하는 감사와 공감의 고급 언어입니다.","m_YshVbe2I4"),
  (57,"Conflict","어려운 대화 이끌기","불편한 주제를 성숙하고 건설적으로 다루는 기술입니다.","t8A3a8j-sY8"),
  (58,"Cultural","유머와 풍자의 문화 차이","문화별 유머 코드를 이해하고 안전하게 활용하는 법입니다.","eX1u6R6pWl4"),
  (59,"Analytical","숫자 없이 설득하는 법","데이터 없이 스토리와 논리만으로 설득하는 고급 기법입니다.","t8A3a8j-sY8"),
  (60,"Review","Month 2 최종 복습 및 평가","31~59일차 전체를 종합 복습하고 성취를 확인합니다.","0I12mA0EejE"),
]

def make_day(day_num, cat, title_str, sub_str, vid):
    return {
        "category": cat,
        "title": f"Day {day_num} - {title_str}",
        "sub": sub_str,
        "videoId": vid,
        "kpis": [
            {"i": "🌟", "v": "Mastery", "l": "마스터리", "d": f"Day {day_num} 핵심 원어민 표현 완전 정복"},
            {"i": "🎯", "v": "Application", "l": "실전 적용", "d": "실제 상황에서 자연스럽게 사용하기"}
        ],
        "lessons": [
            {"t": "핵심 표현 익히기", "d": f"{title_str}에서 원어민이 즐겨 쓰는 핵심 표현"},
            {"t": "뉘앙스 이해하기", "d": "비슷한 표현들 사이의 미묘한 차이 파악"},
            {"t": "문맥 속 활용", "d": "실제 대화 흐름 속에서 자연스럽게 사용하기"},
            {"t": "응용 패턴 연습", "d": "배운 표현을 다양한 상황에 응용하는 연습"},
            {"t": "실수 방지 포인트", "d": "한국인이 자주 하는 실수와 교정 방법"},
            {"t": "원어민 감각 체화", "d": "원어민의 사고방식으로 자연스럽게 발화하기"}
        ],
        "compare": [
            {"b": "I think this is good.", "g": "I'm quite confident this approach will yield strong results."},
            {"b": "Let me explain.", "g": "Allow me to walk you through the reasoning here."},
            {"b": "We need to talk.", "g": "I'd appreciate a moment of your time to discuss something important."},
            {"b": "I don't agree.", "g": "I see it somewhat differently, if I may share my perspective."},
            {"b": "Thank you.", "g": "I truly appreciate your time and thoughtful consideration."},
            {"b": "Good idea.", "g": "That's a genuinely insightful suggestion; I hadn't considered that angle."}
        ],
        "expr": [
            {"e": "I couldn't agree more.", "k": "완전히 동의합니다.", "x": f"Regarding today's point: I couldn't agree more with this approach."},
            {"e": "That gives me pause.", "k": "그 부분은 좀 더 생각해봐야겠네요.", "x": "The timeline you proposed gives me pause; let's revisit it."},
            {"e": "Let's unpack this.", "k": "이 부분을 좀 더 풀어서 살펴봅시다.", "x": "There's a lot here; let's unpack this step by step."},
            {"e": "I'll take that on board.", "k": "그 의견을 반영하겠습니다.", "x": "That's valuable feedback, and I'll take that on board."},
            {"e": "To that end...", "k": "그 목적을 위해...", "x": "We need efficiency; to that end, I propose we streamline the process."},
            {"e": "Worth exploring further.", "k": "더 깊이 살펴볼 가치가 있습니다.", "x": "This is a promising direction; definitely worth exploring further."}
        ]
    }

for (d, cat, title, sub, vid) in themes_41_60:
    days[d] = make_day(d, cat, title, sub, vid)

with open('month2_data.json', 'w', encoding='utf-8') as f:
    json.dump(days, f, ensure_ascii=False, indent=2)

print(f"Generated {len(days)} days: {sorted(days.keys())}")
